/*
 Highcharts JS v5.0.6 (2016-12-07)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(w){"object"===typeof module&&module.exports?module.exports=w:w(Highcharts)})(function(w){(function(a){function q(a,b,d){this.init(a,b,d)}var u=a.each,v=a.extend,l=a.merge,r=a.splat;v(q.prototype,{init:function(a,b,d){var m=this,f=m.defaultOptions;m.chart=b;m.options=a=l(f,b.angular?{background:{}}:void 0,a);(a=a.background)&&u([].concat(r(a)).reverse(),function(b){var c,f=d.userOptions;c=l(m.defaultBackgroundOptions,b);b.backgroundColor&&(c.backgroundColor=b.backgroundColor);c.color=c.backgroundColor;
d.options.plotBands.unshift(c);f.plotBands=f.plotBands||[];f.plotBands!==d.options.plotBands&&f.plotBands.unshift(c)})},defaultOptions:{center:["50%","50%"],size:"85%",startAngle:0},defaultBackgroundOptions:{className:"highcharts-pane",shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"}});a.Pane=q})(w);(function(a){var q=a.CenteredSeriesMixin,
u=a.each,v=a.extend,l=a.map,r=a.merge,e=a.noop,b=a.Pane,d=a.pick,m=a.pInt,f=a.splat,t=a.wrap,c,h,k=a.Axis.prototype;a=a.Tick.prototype;c={getOffset:e,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},setScale:e,setCategories:e,setTitle:e};h={defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},
defaultRadialXOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialYOptions:{gridLineInterpolation:"circle",labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(p){p=this.options=r(this.defaultOptions,this.defaultRadialOptions,p);p.plotBands||(p.plotBands=[])},getOffset:function(){k.getOffset.call(this);this.chart.axisOffset[this.side]=0;this.center=this.pane.center=
q.getCenter.call(this.pane)},getLinePath:function(p,g){p=this.center;var b=this.chart,c=d(g,p[2]/2-this.offset);this.isCircular||void 0!==g?g=this.chart.renderer.symbols.arc(this.left+p[0],this.top+p[1],c,c,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}):(g=this.postTranslate(this.angleRad,c),g=["M",p[0]+b.plotLeft,p[1]+b.plotTop,"L",g.x,g.y]);return g},setAxisTranslation:function(){k.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/
(this.max-this.min||1):this.center[2]/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){if(this.autoConnect=this.isCircular&&void 0===d(this.userMax,this.options.max)&&this.endAngleRad-this.startAngleRad===2*Math.PI)this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0},setAxisSize:function(){k.setAxisSize.call(this);this.isRadial&&(this.center=this.pane.center=q.getCenter.call(this.pane),this.isCircular&&
(this.sector=this.endAngleRad-this.startAngleRad),this.len=this.width=this.height=this.center[2]*d(this.sector,1)/2)},getPosition:function(b,g){return this.postTranslate(this.isCircular?this.translate(b):this.angleRad,d(this.isCircular?g:this.translate(b),this.center[2]/2)-this.offset)},postTranslate:function(b,g){var d=this.chart,c=this.center;b=this.startAngleRad+b;return{x:d.plotLeft+c[0]+Math.cos(b)*g,y:d.plotTop+c[1]+Math.sin(b)*g}},getPlotBandPath:function(b,g,c){var p=this.center,f=this.startAngleRad,
k=p[2]/2,n=[d(c.outerRadius,"100%"),c.innerRadius,d(c.thickness,10)],a=Math.min(this.offset,0),h=/%$/,t,e=this.isCircular;"polygon"===this.options.gridLineInterpolation?p=this.getPlotLinePath(b).concat(this.getPlotLinePath(g,!0)):(b=Math.max(b,this.min),g=Math.min(g,this.max),e||(n[0]=this.translate(b),n[1]=this.translate(g)),n=l(n,function(b){h.test(b)&&(b=m(b,10)*k/100);return b}),"circle"!==c.shape&&e?(b=f+this.translate(b),g=f+this.translate(g)):(b=-Math.PI/2,g=1.5*Math.PI,t=!0),n[0]-=a,n[2]-=
a,p=this.chart.renderer.symbols.arc(this.left+p[0],this.top+p[1],n[0],n[0],{start:Math.min(b,g),end:Math.max(b,g),innerR:d(n[1],n[0]-n[2]),open:t}));return p},getPlotLinePath:function(b,g){var c=this,d=c.center,m=c.chart,p=c.getPosition(b),f,k,a;c.isCircular?a=["M",d[0]+m.plotLeft,d[1]+m.plotTop,"L",p.x,p.y]:"circle"===c.options.gridLineInterpolation?(b=c.translate(b))&&(a=c.getLinePath(0,b)):(u(m.xAxis,function(b){b.pane===c.pane&&(f=b)}),a=[],b=c.translate(b),d=f.tickPositions,f.autoConnect&&(d=
d.concat([d[0]])),g&&(d=[].concat(d).reverse()),u(d,function(c,g){k=f.getPosition(c,b);a.push(g?"L":"M",k.x,k.y)}));return a},getTitlePosition:function(){var b=this.center,c=this.chart,d=this.options.title;return{x:c.plotLeft+b[0]+(d.x||0),y:c.plotTop+b[1]-{high:.5,middle:.25,low:0}[d.align]*b[2]+(d.y||0)}}};t(k,"init",function(m,g,k){var p=g.angular,a=g.polar,n=k.isX,t=p&&n,e,x=g.options,l=k.pane||0;if(p){if(v(this,t?c:h),e=!n)this.defaultRadialOptions=this.defaultRadialGaugeOptions}else a&&(v(this,
h),this.defaultRadialOptions=(e=n)?this.defaultRadialXOptions:r(this.defaultYAxisOptions,this.defaultRadialYOptions));p||a?(this.isRadial=!0,g.inverted=!1,x.chart.zoomType=null):this.isRadial=!1;m.call(this,g,k);t||!p&&!a||(m=this.options,g.panes||(g.panes=[]),this.pane=g=g.panes[l]=g.panes[l]||new b(f(x.pane)[l],g,this),g=g.options,this.angleRad=(m.angle||0)*Math.PI/180,this.startAngleRad=(g.startAngle-90)*Math.PI/180,this.endAngleRad=(d(g.endAngle,g.startAngle+360)-90)*Math.PI/180,this.offset=m.offset||
0,this.isCircular=e)});t(k,"autoLabelAlign",function(b){if(!this.isRadial)return b.apply(this,[].slice.call(arguments,1))});t(a,"getPosition",function(b,c,d,m,f){var g=this.axis;return g.getPosition?g.getPosition(d):b.call(this,c,d,m,f)});t(a,"getLabelPosition",function(b,c,m,f,k,a,h,t,e){var g=this.axis,p=a.y,n=20,x=a.align,z=(g.translate(this.pos)+g.startAngleRad+Math.PI/2)/Math.PI*180%360;g.isRadial?(b=g.getPosition(this.pos,g.center[2]/2+d(a.distance,-25)),"auto"===a.rotation?f.attr({rotation:z}):
null===p&&(p=g.chart.renderer.fontMetrics(f.styles.fontSize).b-f.getBBox().height/2),null===x&&(g.isCircular?(this.label.getBBox().width>g.len*g.tickInterval/(g.max-g.min)&&(n=0),x=z>n&&z<180-n?"left":z>180+n&&z<360-n?"right":"center"):x="center",f.attr({align:x})),b.x+=a.x,b.y+=p):b=b.call(this,c,m,f,k,a,h,t,e);return b});t(a,"getMarkPath",function(b,c,d,m,f,a,k){var g=this.axis;g.isRadial?(b=g.getPosition(this.pos,g.center[2]/2+m),c=["M",c,d,"L",b.x,b.y]):c=b.call(this,c,d,m,f,a,k);return c})})(w);
(function(a){var q=a.each,u=a.noop,v=a.pick,l=a.Series,r=a.seriesType,e=a.seriesTypes;r("arearange","area",{lineWidth:1,marker:null,threshold:null,tooltip:{pointFormat:'\x3cspan style\x3d"color:{series.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0},states:{hover:{halo:!1}}},{pointArrayMap:["low","high"],dataLabelCollections:["dataLabel",
"dataLabelUpper"],toYData:function(b){return[b.low,b.high]},pointValKey:"low",deferTranslatePolar:!0,highToXY:function(b){var d=this.chart,m=this.xAxis.postTranslate(b.rectPlotX,this.yAxis.len-b.plotHigh);b.plotHighX=m.x-d.plotLeft;b.plotHigh=m.y-d.plotTop},translate:function(){var b=this,d=b.yAxis,m=!!b.modifyValue;e.area.prototype.translate.apply(b);q(b.points,function(f){var a=f.low,c=f.high,h=f.plotY;null===c||null===a?f.isNull=!0:(f.plotLow=h,f.plotHigh=d.translate(m?b.modifyValue(c,f):c,0,1,
0,1),m&&(f.yBottom=f.plotHigh))});this.chart.polar&&q(this.points,function(d){b.highToXY(d)})},getGraphPath:function(b){var d=[],m=[],f,a=e.area.prototype.getGraphPath,c,h,k;k=this.options;var p=k.step;b=b||this.points;for(f=b.length;f--;)c=b[f],c.isNull||k.connectEnds||b[f+1]&&!b[f+1].isNull||m.push({plotX:c.plotX,plotY:c.plotY,doCurve:!1}),h={polarPlotY:c.polarPlotY,rectPlotX:c.rectPlotX,yBottom:c.yBottom,plotX:v(c.plotHighX,c.plotX),plotY:c.plotHigh,isNull:c.isNull},m.push(h),d.push(h),c.isNull||
k.connectEnds||b[f-1]&&!b[f-1].isNull||m.push({plotX:c.plotX,plotY:c.plotY,doCurve:!1});b=a.call(this,b);p&&(!0===p&&(p="left"),k.step={left:"right",center:"center",right:"left"}[p]);d=a.call(this,d);m=a.call(this,m);k.step=p;k=[].concat(b,d);this.chart.polar||"M"!==m[0]||(m[0]="L");this.graphPath=k;this.areaPath=this.areaPath.concat(b,m);k.isArea=!0;k.xMap=b.xMap;this.areaPath.xMap=b.xMap;return k},drawDataLabels:function(){var b=this.data,d=b.length,m,a=[],t=l.prototype,c=this.options.dataLabels,
h=c.align,k=c.verticalAlign,p=c.inside,g,n,e=this.chart.inverted;if(c.enabled||this._hasPointLabels){for(m=d;m--;)if(g=b[m])n=p?g.plotHigh<g.plotLow:g.plotHigh>g.plotLow,g.y=g.high,g._plotY=g.plotY,g.plotY=g.plotHigh,a[m]=g.dataLabel,g.dataLabel=g.dataLabelUpper,g.below=n,e?h||(c.align=n?"right":"left"):k||(c.verticalAlign=n?"top":"bottom"),c.x=c.xHigh,c.y=c.yHigh;t.drawDataLabels&&t.drawDataLabels.apply(this,arguments);for(m=d;m--;)if(g=b[m])n=p?g.plotHigh<g.plotLow:g.plotHigh>g.plotLow,g.dataLabelUpper=
g.dataLabel,g.dataLabel=a[m],g.y=g.low,g.plotY=g._plotY,g.below=!n,e?h||(c.align=n?"left":"right"):k||(c.verticalAlign=n?"bottom":"top"),c.x=c.xLow,c.y=c.yLow;t.drawDataLabels&&t.drawDataLabels.apply(this,arguments)}c.align=h;c.verticalAlign=k},alignDataLabel:function(){e.column.prototype.alignDataLabel.apply(this,arguments)},setStackedPoints:u,getSymbol:u,drawPoints:u})})(w);(function(a){var q=a.seriesType;q("areasplinerange","arearange",null,{getPointSpline:a.seriesTypes.spline.prototype.getPointSpline})})(w);
(function(a){var q=a.defaultPlotOptions,u=a.each,v=a.merge,l=a.noop,r=a.pick,e=a.seriesType,b=a.seriesTypes.column.prototype;e("columnrange","arearange",v(q.column,q.arearange,{lineWidth:1,pointRange:null}),{translate:function(){var d=this,m=d.yAxis,a=d.xAxis,t=a.startAngleRad,c,h=d.chart,k=d.xAxis.isRadial,p;b.translate.apply(d);u(d.points,function(b){var g=b.shapeArgs,f=d.options.minPointLength,e,l;b.plotHigh=p=m.translate(b.high,0,1,0,1);b.plotLow=b.plotY;l=p;e=r(b.rectPlotY,b.plotY)-p;Math.abs(e)<
f?(f-=e,e+=f,l-=f/2):0>e&&(e*=-1,l-=e);k?(c=b.barX+t,b.shapeType="path",b.shapeArgs={d:d.polarArc(l+e,l,c,c+b.pointWidth)}):(g.height=e,g.y=l,b.tooltipPos=h.inverted?[m.len+m.pos-h.plotLeft-l-e/2,a.len+a.pos-h.plotTop-g.x-g.width/2,e]:[a.left-h.plotLeft+g.x+g.width/2,m.pos-h.plotTop+l+e/2,e])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:l,crispCol:b.crispCol,drawPoints:b.drawPoints,drawTracker:b.drawTracker,getColumnMetrics:b.getColumnMetrics,animate:function(){return b.animate.apply(this,
arguments)},polarArc:function(){return b.polarArc.apply(this,arguments)},pointAttribs:b.pointAttribs})})(w);(function(a){var q=a.each,u=a.isNumber,v=a.merge,l=a.pick,r=a.pInt,e=a.Series,b=a.seriesType,d=a.TrackerMixin;b("gauge","line",{dataLabels:{enabled:!0,defer:!1,y:15,borderRadius:3,crop:!1,verticalAlign:"top",zIndex:2,borderWidth:1,borderColor:"#cccccc"},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:a.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,
trackerGroups:["group","dataLabelsGroup"],translate:function(){var b=this.yAxis,d=this.options,a=b.center;this.generatePoints();q(this.points,function(c){var m=v(d.dial,c.dial),k=r(l(m.radius,80))*a[2]/200,f=r(l(m.baseLength,70))*k/100,g=r(l(m.rearLength,10))*k/100,n=m.baseWidth||3,t=m.topWidth||1,e=d.overshoot,q=b.startAngleRad+b.translate(c.y,null,null,null,!0);u(e)?(e=e/180*Math.PI,q=Math.max(b.startAngleRad-e,Math.min(b.endAngleRad+e,q))):!1===d.wrap&&(q=Math.max(b.startAngleRad,Math.min(b.endAngleRad,
q)));q=180*q/Math.PI;c.shapeType="path";c.shapeArgs={d:m.path||["M",-g,-n/2,"L",f,-n/2,k,-t/2,k,t/2,f,n/2,-g,n/2,"z"],translateX:a[0],translateY:a[1],rotation:q};c.plotX=a[0];c.plotY=a[1]})},drawPoints:function(){var b=this,d=b.yAxis.center,a=b.pivot,c=b.options,h=c.pivot,k=b.chart.renderer;q(b.points,function(d){var g=d.graphic,a=d.shapeArgs,m=a.d,f=v(c.dial,d.dial);g?(g.animate(a),a.d=m):(d.graphic=k[d.shapeType](a).attr({rotation:a.rotation,zIndex:1}).addClass("highcharts-dial").add(b.group),d.graphic.attr({stroke:f.borderColor||
"none","stroke-width":f.borderWidth||0,fill:f.backgroundColor||"#000000"}))});a?a.animate({translateX:d[0],translateY:d[1]}):(b.pivot=k.circle(0,0,l(h.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(d[0],d[1]).add(b.group),b.pivot.attr({"stroke-width":h.borderWidth||0,stroke:h.borderColor||"#cccccc",fill:h.backgroundColor||"#000000"}))},animate:function(b){var d=this;b||(q(d.points,function(b){var c=b.graphic;c&&(c.attr({rotation:180*d.yAxis.startAngleRad/Math.PI}),c.animate({rotation:b.shapeArgs.rotation},
d.options.animation))}),d.animate=null)},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);e.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(b,d){e.prototype.setData.call(this,b,!1);this.processData();this.generatePoints();l(d,!0)&&this.chart.redraw()},drawTracker:d&&d.drawTrackerPoint},{setState:function(b){this.state=b}})})(w);(function(a){var q=a.each,u=a.noop,v=a.pick,l=a.seriesType,
r=a.seriesTypes;l("boxplot","column",{threshold:null,tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eMaximum: {point.high}\x3cbr/\x3eUpper quartile: {point.q3}\x3cbr/\x3eMedian: {point.median}\x3cbr/\x3eLower quartile: {point.q1}\x3cbr/\x3eMinimum: {point.low}\x3cbr/\x3e'},whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,states:{hover:{brightness:-.3}},whiskerWidth:2},{pointArrayMap:["low","q1","median",
"q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(a){var b=this.options,d=a&&a.color||this.color;return{fill:a.fillColor||b.fillColor||d,stroke:b.lineColor||d,"stroke-width":b.lineWidth||0}},drawDataLabels:u,translate:function(){var a=this.yAxis,b=this.pointArrayMap;r.column.prototype.translate.apply(this);q(this.points,function(d){q(b,function(b){null!==d[b]&&(d[b+"Plot"]=a.translate(d[b],0,1,0,1))})})},drawPoints:function(){var a=
this,b=a.options,d=a.chart.renderer,m,f,t,c,h,k,p=0,g,n,l,r,B=!1!==a.doQuartiles,u,y=a.options.whiskerLength;q(a.points,function(e){var q=e.graphic,z=q?"animate":"attr",x=e.shapeArgs,w={},D={},H={},I=e.color||a.color;void 0!==e.plotY&&(g=x.width,n=Math.floor(x.x),l=n+g,r=Math.round(g/2),m=Math.floor(B?e.q1Plot:e.lowPlot),f=Math.floor(B?e.q3Plot:e.lowPlot),t=Math.floor(e.highPlot),c=Math.floor(e.lowPlot),q||(e.graphic=q=d.g("point").add(a.group),e.stem=d.path().addClass("highcharts-boxplot-stem").add(q),
y&&(e.whiskers=d.path().addClass("highcharts-boxplot-whisker").add(q)),B&&(e.box=d.path(void 0).addClass("highcharts-boxplot-box").add(q)),e.medianShape=d.path(void 0).addClass("highcharts-boxplot-median").add(q),w.stroke=e.stemColor||b.stemColor||I,w["stroke-width"]=v(e.stemWidth,b.stemWidth,b.lineWidth),w.dashstyle=e.stemDashStyle||b.stemDashStyle,e.stem.attr(w),y&&(D.stroke=e.whiskerColor||b.whiskerColor||I,D["stroke-width"]=v(e.whiskerWidth,b.whiskerWidth,b.lineWidth),e.whiskers.attr(D)),B&&(q=
a.pointAttribs(e),e.box.attr(q)),H.stroke=e.medianColor||b.medianColor||I,H["stroke-width"]=v(e.medianWidth,b.medianWidth,b.lineWidth),e.medianShape.attr(H)),k=e.stem.strokeWidth()%2/2,p=n+r+k,e.stem[z]({d:["M",p,f,"L",p,t,"M",p,m,"L",p,c]}),B&&(k=e.box.strokeWidth()%2/2,m=Math.floor(m)+k,f=Math.floor(f)+k,n+=k,l+=k,e.box[z]({d:["M",n,f,"L",n,m,"L",l,m,"L",l,f,"L",n,f,"z"]})),y&&(k=e.whiskers.strokeWidth()%2/2,t+=k,c+=k,u=/%$/.test(y)?r*parseFloat(y)/100:y/2,e.whiskers[z]({d:["M",p-u,t,"L",p+u,t,
"M",p-u,c,"L",p+u,c]})),h=Math.round(e.medianPlot),k=e.medianShape.strokeWidth()%2/2,h+=k,e.medianShape[z]({d:["M",n,h,"L",l,h]}))})},setStackedPoints:u})})(w);(function(a){var q=a.each,u=a.noop,v=a.seriesType,l=a.seriesTypes;v("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.hi